test_color_name_to_hex (__main__.TestExercice) ... ERROR
test_compute_mse (__main__.TestExercice) ... FAIL
test_create_list (__main__.TestExercice) ... ERROR
test_list_to_dict (__main__.TestExercice) ... ok

======================================================================
ERROR: test_color_name_to_hex (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 34, in test_color_name_to_hex
    output = [exercice.color_name_to_hex(v) for v in colors]
  File "test_exercice.py", line 34, in <listcomp>
    output = [exercice.color_name_to_hex(v) for v in colors]
  File "/home/runner/work/c04-ch6-exercices-2-chibi20/c04-ch6-exercices-2-chibi20/exercice.py", line 21, in color_name_to_hex
    tuple_couleur = (colors[i], hex(colors[i]))
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_create_list (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 44, in test_create_list
    output = exercice.create_list()
  File "/home/runner/work/c04-ch6-exercices-2-chibi20/c04-ch6-exercices-2-chibi20/exercice.py", line 33, in create_list
    liste[i] = i
IndexError: list assignment index out of range

======================================================================
FAIL: test_compute_mse (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 65, in test_compute_mse
    'Erreur dans le calcul des MSE'
AssertionError: {} != {'LR': 220.6, 'DNN': 14.0, 'RF': 1681.8}
- {}
+ {'DNN': 14.0, 'LR': 220.6, 'RF': 1681.8} : Erreur dans le calcul des MSE

----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (failures=1, errors=2)
